name: Tauri Test Beta CI

on:
  push:
    branches:
      - beta

jobs:
  build:
    uses: larrygogo/github-actions/.github/workflows/tauri-template.yml@main
    with:
      projectName: "tauri-test"
      buildStage: "beta"
      nodeVersion: 20
      buildFeishuWebhook: "https://open.feishu.cn/open-apis/bot/v2/hook/2d66d885-547c-4695-abdb-0ebc89a3eb92"
    secrets:
      ossAccessKey: ${{ secrets.OSS_ACCESS_KEY }}
      ossAccessKeySecret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      tauriPrivateKey: ${{ secrets.TAURI_PRIVATE_KEY }}
      tauriKeyPassword: ${{ secrets.TAURI_PUBLIC_KEY }}
